apiVersion: v1
kind: Template
metadata:
  name: thoth-container-analyzer-template
  annotations:
  description: This is a container analyzer job for Thoth Core
  openshift.io/display-name: "Thoth Core: Analyzer"
  version: 0.0.1
  template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: thoth-core
    app: thoth-analyzer

objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: container-analyzer
      labels:
        app: thoth-analyzer
    spec:
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 500m
          memory: 512Mi
      output:
        to:
          kind: ImageStreamTag
          name: 'container-analyzer:latest'
      source:
        type: Git
        git:
          uri: 'https://github.com/ace2107/Container_analyzer'
          ref: master
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: container-analyzer-python-36-centos7:latest
          pullSecret:
            name: "upshift"
          env:
            - name: ENABLE_PIPENV
              value: '1'
      triggers:
        - type: ImageChange
          imageChange: {}

  - kind: ImageStream
    apiVersion: v1
    metadata:
      labels:
        app: thoth-analyzer
      name: container-analyzer
    spec:
      name: latest
      lookupPolicy:
        local: true

  - apiVersion: batch/v2alpha1
    kind: CronJob
    metadata:
      name:  container-analyzer
      labels:
        app: thoth-analyzer
        name:  container-analyzer
    spec:
      schedule: "* * * * *"
      suspend : false
      concurrencyPolicy: Forbid
      successfulJobsHistoryLimit: 2
      failedJobsHistoryLimit: 1
      jobTemplate:
        spec:
          template:
            spec:
              containers:
              - image: container-analyzer
                name: container-analyzer
                resources:
                  limits:
                    memory: '128Mi'
                    cpu: '250m'
                  requests:
                    memory: '128Mi'
                    cpu: '250m'
                env:
                - name: REGISTRY_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: registry-token
                      name: registry-token
                - name: JH_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: jh-token
                      name: jh-token
              restartPolicy: OnFailure
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: container-analyzer-python-36-centos7
      labels:
        app: thoth-analyzer
    spec:
      lookupPolicy:
        local: false
      tags:
        - from:
            kind: DockerImage
            name: registry.centos.org/centos/python-36-centos7
          name: latest
          referencePolicy:
            type: Source
