apiVersion: v1
kind: Template
labels:
  template: container-analyzer-buildconfig
  thoth: 0.1.0
metadata:
  name: container-analyzer-buildconfig
  annotations:
    description: This is Thoth Core - Container analyzer BuildConfig
    openshift.io/display-name: "Thoth: COntainer analyzer BuildConfig"
    version: 0.3.0
    tags: poc,thoth,ai-stacks,package-extract,graph,janusgraph
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: |-
      This template defines resources needed to deploy Thoth
      Package Extract as a Proof-of-Concept to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: container-analyzer-job
    labels:
      app: thoth-core
  spec:
    resources:
      requests:
        cpu: 1
        memory: 512Mi
      limits:
        cpu: 2
        memory: 1024Mi
    output:
      to:
        kind: ImageStreamTag
        name: "container-analyzer-job:${IMAGE_STREAM_TAG}"
    source:
      type: Git
      git:
        uri: "${GITHUB_URL}"
        ref: "${GITHUB_REF}"
    strategy:
      type: S2I
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: "container-analyzer-base:${IMAGE_STREAM_TAG}"
        imageOptimizationPolicy: SkipLayers
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}

parameters:
- description: Name of the github repository
  displayName: Git Repository
  required: true
  name: GITHUB_URL
  value: 'https://github.com/ace2107/Container_analyzer'

- description: Git reference to be used
  displayName: Git Reference
  required: true
  name: GITHUB_REF
  value: 'master'

- description: |-
    Tag of the output ImageStream the resulting container image should go to
  displayName: ImageStream Tag
  required: true
  name: IMAGE_STREAM_TAG
  value: 'latest'
