apiVersion: v1
kind: Template
labels:
  template: container-analyzer-imagestream
  thoth: 0.1.0
metadata:
  name: container-analyzer-imagestream
  annotations:
    description: This is Thoth Core - Container Analyzer ImageStream
    openshift.io/display-name: "Thoth: Container Analyzer ImageStream"
    version: 0.1.3
    tags: poc,thoth,ai-stacks,container-analyzer
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: |-
      This template defines resources needed to deploy Thoth Package
      Extract as a Proof-of-Concept to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: thoth-core
    name: container-analyzer-base
  spec:
    name: latest
    dockerImageRepository: registry.centos.org/centos/python-36-centos7

- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: thoth-core
    name: container-analyzer-job
  spec:
    name: latest
    lookupPolicy:
      local: true